[project]
name = "Lotter-app"
version = "0.1.3"
description = "Lotter application."
requires-python = ">=3.12.12"
authors = [
    { name = "JogFeelingVI", email = "glifelse@gmail.com" }
]

dependencies = [
  "flet>=0.80.4",
  "flet-desktop>=0.80.4",
  "flet-web>=0.80.4",
]

[tool.flet]
path = "main.py" # 明确指定入口文件
bundle_id = "com.flet.lotter-app"

[tool.uv]
managed = true # 声明由 uv 管理

